
### Playing around with Gordon Hayward NBA data ###
Purpose is to get more familiar with Jupyter and Python

In [ ]:
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.endpoints import playergamelogs
career = playercareerstats.PlayerCareerStats(player_id='202330')
# Gordon Hayward, taken from nba.com
career.get_data_frames()[0]

In [32]:
gamelog = playergamelogs.PlayerGameLogs(player_id_nullable='202330')
log = gamelog.get_data_frames()[0]

In [26]:
log

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,VIDEO_AVAILABLE_FLAG
0,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021601227,2017-04-12T00:00:00,UTA vs. SAS,...,1,10,61,59,31,63,3,1,68,1
1,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021601194,2017-04-08T00:00:00,UTA @ POR,...,41,35,12,42,67,48,3,1,51,1
2,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021601185,2017-04-07T00:00:00,UTA vs. MIN,...,1,60,12,1,20,1,3,1,1,1
3,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021601164,2017-04-04T00:00:00,UTA vs. POR,...,41,1,44,10,20,28,3,1,20,1
4,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021601151,2017-04-02T00:00:00,UTA @ SAS,...,41,60,61,56,49,60,3,1,59,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021600136,2016-11-12T00:00:00,UTA @ MIA,...,41,10,6,25,5,23,3,1,26,1
69,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021600124,2016-11-11T00:00:00,UTA @ ORL,...,67,10,22,43,12,14,1,1,20,1
70,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021600108,2016-11-09T00:00:00,UTA @ CHA,...,1,60,12,14,58,15,3,1,8,1
71,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021600093,2016-11-07T00:00:00,UTA @ PHI,...,1,35,44,43,12,37,3,1,43,1
72,2016-17,202330,Gordon Hayward,Gordon,1610612762,UTA,Utah Jazz,0021600087,2016-11-06T00:00:00,UTA @ NYK,...,1,60,6,16,34,48,3,1,39,1